apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 labels:
   app: backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backend
 template:
   metadata:
     labels:
       app: backend
   spec:
     containers:
     - name: fastapibackend
       image: fullstack_fastapi_img:latest
       imagePullPolicy: Never
       ports:
       - containerPort: 8000
