kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app-frontend
          image: fullstack_react_img:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
      restartPolicy: Always
